server.undertow.threads.io=3
server.undertow.threads.worker=200
server.undertow.direct-buffers=true
server.undertow.max-http-post-size=1MB
server.undertow.options.socket.SEND_BUFFER=8192
server.undertow.options.socket.WRITE_TIMEOUT=5000
logging.level.root=WARN